includes:
  - configs/gui.yml
  - configs/git.yml
  - configs/update.yml
  - configs/refresher.yml
  - configs/os.yml
  - configs/customCommands.yml
  - configs/services.yml
  - configs/keybindings.yml

# General top-level options
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: false
notARepository: prompt
promptToReturnFromSubprocess: true
