os:
  edit: ""
  editAtLine: ""
  editAtLineAndWait: ""
  editInTerminal: false
  openDirInEditor: ""
  editPreset: ""
  open: ""
  openLink: ""
  copyToClipboardCmd: ""
  readFromClipboardCmd: ""
  shellFunctionsFile: ""
